version: '3'
services:
  youapp:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - docker.env
    ports:
      - '3000:3000'
    depends_on:
      - db
  db:
    image: mongo
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - ./data:/data/db
